Hm3
userapk1/EvgenyZinovev_LevelUP pull request #6
Opened 2023-03-07 16:51 UTC by userapk1

working! running tests on a package

2023-03-14 08:37 UTC, khda91 requested changes
Исправь пожалуйста замечания к работе. 
Во всех селениум тестах ошибки типовые, так что описал их только в одном классе

2023-03-14 08:37 UTC, khda91 commented on src/main/java/ticket/test/hm2/TicketImpl.java
> +    public String sumNumb(String input) {
А почему возвращается `String`, а не `boolean`

2023-03-14 08:37 UTC, khda91 commented on src/main/java/ticket/test/hm2/TicketImpl.java
> +            return "false";
Тут можно чуть проще `return sum1 == sum2`

2023-03-14 08:37 UTC, khda91 commented on src/main/java/ticket/test/hm2/TicketImpl.java
> +        return "Номер билета должен состоять из 6 цифр";
Ошибка должна возвращаться не просто строкой, а должен выбрасываться `Exception`

2023-03-14 08:37 UTC, khda91 commented on src/test/java/ticket/test/hm2/BaseTicketTest.java
> +        expected = new String("Номер билета должен состоять из 6 цифр");
expected = "Номер билета должен состоять из 6 цифр";

2023-03-14 08:37 UTC, khda91 commented on src/test/java/ticket/test/hm2/TicketNegativeTest.java
> +        Assertions.assertThrows(NullPointerException.class,
`NullPointerException` должен обрабатываться в коде метода, который вычисляет счасливое число, а не выбрасываться

2023-03-14 08:37 UTC, khda91 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +        SleepUtils.sleep(2000);
В коде не должно быть никаких Thread.sleep

2023-03-14 08:37 UTC, khda91 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +            .sleep(2000);
Не должно быть никаких thread.sleep

2023-03-14 08:37 UTC, khda91 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +            .sendKeys(bodyLetter);
Зачем используется здесь индексация

2023-03-14 08:37 UTC, khda91 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +            .xpath("//div[contains(@class, 'style')]//div[contains(@class, 'js-helper')]/div/div/div/div[1]")))
Зачем в локаторе используется индексация?

2023-03-14 08:45 UTC, userapk1 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +            .sendKeys(bodyLetter);
по-другому не получается найти нужный элемент, т.к. их там 3, а нужен конкретно второй

2023-03-14 08:46 UTC, userapk1 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +        SleepUtils.sleep(2000);
без слипов хотя бы в 1сек селениум не успевает обнаружить все элементы. мб из-за высокой скорости соединения

2023-03-14 08:46 UTC, userapk1 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +            .sleep(2000);
без слипов хотя бы в 1сек селениум не успевает обнаружить все элементы. мб из-за высокой скорости соединения

2023-03-14 08:48 UTC, userapk1 commented on src/test/java/selenium/basic/test/hm3/exercise/ExeciseThree.java
> +            .xpath("//div[contains(@class, 'style')]//div[contains(@class, 'js-helper')]/div/div/div/div[1]")))
по-другому не получается найти нужный элемент, т.к. их там 3, а нужен конкретно первый
попробую найти способ успешнее, но не уверен, что получится

2023-03-14 17:35 UTC, userapk1 commented
обновлен код по 3 дз. Посмотри, пожалуйста, комменты
по 2 внесу исправления - сделаю отдельный пулл - укажу в таблице

2023-03-14 17:36 UTC, merged

2023-03-14 17:37 UTC, userapk1 commented
блин, я по незнанию смержил в мейн..

2023-04-22 20:36 UTC, userapk1 commented on src/main/java/ticket/test/hm2/TicketImpl.java
> +    public String sumNumb(String input) {
исправлено

2023-04-22 20:36 UTC, userapk1 commented on src/main/java/ticket/test/hm2/TicketImpl.java
> +            return "false";
реализовано иначе

2023-04-22 20:36 UTC, userapk1 commented on src/main/java/ticket/test/hm2/TicketImpl.java
> +        return "Номер билета должен состоять из 6 цифр";
исправлено

2023-04-22 20:37 UTC, userapk1 commented on src/test/java/ticket/test/hm2/BaseTicketTest.java
> +        expected = new String("Номер билета должен состоять из 6 цифр");
реализовано иначе

2023-04-22 20:37 UTC, userapk1 commented on src/test/java/ticket/test/hm2/TicketNegativeTest.java
> +        Assertions.assertThrows(NullPointerException.class,
исправлено